version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: leaderboard
    ports:
      - "5432:5432"
  app:
    build: .
    environment:
      DATABASE_URL: postgres://username:password@db:5432/leaderboard
      JWT_SECRET: jwt_secret
    depends_on:
      - db
    ports:
      - "8000:8000"
